.github/workflows/pipeline.yaml
Changed testing and prod stack names.
=> Pipeline Changes

README.md
* I have tried to set up the project locally to contribute to it.
* I faced a few issues while setting up the project
* I tried to add a few lines to the **readme** that would help the people who are setting up the development server in their local environment.
* Kindly, suggest to me if I have to make any alterations to the PR.
=> Added : Errors while running local dev environment

.github/workflows/pipeline.yaml
=> Pipeline Fixed

template.yaml, verify/main.go
=> Added SSM Policies

.github/workflows/pipeline.yaml
=> New Pipeline created

profile/main.go
=> Add condition to check last rejected diff

profile/main.go
[ ] Refactored the code to show the report.
=> Refactored the code for Show Report

profile/main.go
closes: #143 
Add a DOB field in profile and profile diff.
For reasons Please use the above issue
=> add dob field

profile/main.go
Reverts Real-Dev-Squad/identity-service#144
=> Revert "add dob field"

verify/main.go, verify/main_test.go
PR Merged in develop
#175 - Changes to the verify function
=> Dev to main sync

README.md, template.yaml
Date: 16/01/2024 
---
Closes #183 
Migrated the project to Al2023 runtime for better build time and security.
=> Migrated the project to Al2023 runtime

template.yaml
Date: 04/02/2024
---
Increasing the timeout of every function 60 seconds
=> Increasing the timeout to 60 seconds

call-profile/main.go, verify/main.go
Date: 26/03/2024
Developer Name: @MehulKChaudhari 
---
PRs going in:
- #205
=> Dev to Main

verify/main_test.go
Date: 
Developer Name: Kavya Rishi
---
PR going in:  https://github.com/Real-Dev-Squad/identity-service/pull/211
=> DEV to MAIN sync 

layer/utils/firestore.go, layer/utils/logging.go
Date: 16/09/2024
---
Profile diff is stored in the wrong collection and resolved. I should be stored in the profileDiffs collection.
=> Profile diff storing in wrong collection resolved

.github/workflows/pipeline.yaml
Date: 16/09/2024
---
Changed the upload artifact version from 2 to 3
=> Changed the artifact version from 2 to 3

layer/utils/validation.go
Date: 16/09/2024
---
Added approval status to new Diff
=> Added approval status to new Diff

.github/workflows/pipeline.yaml, .github/workflows/test.yml
Date: 29/05/2025
---
#231 
Updated the workflow actions versions to latest
=> fix: workflows version update

scripts/dev.sh
Date: 9-6-2025
Developer Name: @vinit717 
---
https://github.com/Real-Dev-Squad/identity-service/issues/227
Update the dev script to support cross-platform 
<details>
<summary>
</summary>
</details>
<details>
<summary>Screenshot 1</summary>
</details>
=> Update dev.sh to support cross-platform

scripts/dev.sh, scripts/test.sh
Date: 13/06/2025
---
#214 
Dev to main
Enhance the test script to include test coverage reporting for both the Health and Verify modules and refine the execution with local tools.
The changes ensure that test coverage metrics are generated and displayed, aiding in quality assessment and allowing for more informed decisions based on test completeness. The switch from global npm installations to local execution helps avoid dependency conflicts and improves the script's reliability in different environments.
> Is this description stale? Ask me to generate a new description by commenting `/korbit-generate-pr-description`
=> Dev to main (Test Coverage)
